- hosts: all
  gather_facts: no
  vars:
  tasks:
   - name: Clone Git Repository
     git:
      repo: 'https://github.com/netbox-community/netbox-docker.git'
      dest: /tmp/netbox-docker
   - name: copy config netbox
     copy:
       remote_src: /tmp/netbox-docker/docker-compose.override.yml.example
       remote_dest: /tmp/netbox-docker/docker-compose.override.yml
     become: yes
  
   - name: Docker Pull Images
     docker_compose:
        project_src: /tmp/netbox-docker/
        state: absent
        pull: yes

   - name: Create and start services Netbox
     docker_compose:
       project_src: /tmp/netbox-docker/
