- hosts: all
  gather_facts: no
  tasks:
  - name: Install python3-pip
    yum:
      name: python3-pip
      state: latest

  - name: Install libselinux-python3
    yum:
      name: libselinux-python3
      state: latest

  - name: Install docker-compose
    pip:
      name: docker-compose
      state: latest